import type {
  RolePermissions,
  RoleWorkspaceFile,
  RoleWorkspaceScaffold,
  RoleWorkspaceScaffolds,
  TeamHandoff,
  TeamPackageStatus,
  TeamWorkPackage
} from "./types";

type ScaffoldSummaryCounts = Pick<
  RoleWorkspaceScaffolds["summary"],
  "ready" | "needsApproval" | "blocked" | "templates"
>;

export function buildRoleWorkspaceScaffolds({
  handoff,
  generatedAt = handoff.generatedAt
}: {
  handoff: TeamHandoff;
  generatedAt?: string;
}): RoleWorkspaceScaffolds {
  const scaffolds = handoff.packages.map((workPackage) =>
    buildRoleWorkspaceScaffold(workPackage, generatedAt)
  );
  const counts = scaffolds.reduce<ScaffoldSummaryCounts>((next, scaffold) => {
    const key = summaryKey(scaffold.status);
    return {
      ...next,
      [key]: next[key] + 1
    };
  }, {
    ready: 0,
    needsApproval: 0,
    blocked: 0,
    templates: 0
  });

  return {
    schema: "naikaku.role-workspace-scaffolds.v1",
    generatedAt,
    mission: handoff.mission,
    runId: handoff.runId,
    scaffolds,
    summary: {
      roles: scaffolds.length,
      files: scaffolds.reduce((total, scaffold) => total + scaffold.files.length, 0),
      ...counts,
      envFiles: scaffolds.reduce(
        (total, scaffold) => total + scaffold.files.filter((file) => file.purpose === "env-example").length,
        0
      ),
      runnerNotes: scaffolds.reduce(
        (total, scaffold) => total + scaffold.files.filter((file) => file.purpose === "runner-notes").length,
        0
      )
    }
  };
}

export function serializeRoleWorkspaceScaffolds(scaffolds: RoleWorkspaceScaffolds) {
  return JSON.stringify(scaffolds, null, 2);
}

export function serializeRoleWorkspaceScaffoldScript(scaffolds: RoleWorkspaceScaffolds) {
  const lines = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "# Generated by Naikaku AI Togo System.",
    "# Creates reviewable role workspace starter files only.",
    "# No raw API secrets are embedded in this script.",
    ""
  ];

  scaffolds.scaffolds.forEach((scaffold) => {
    lines.push(`# Role workspace: ${oneLine(scaffold.roleName)} (${oneLine(scaffold.roleId)})`);
    lines.push(`mkdir -p ${shellQuote(scaffold.rootPath)}`);
    scaffold.files.forEach((file, index) => {
      const delimiter = heredocDelimiter(file.content, scaffold.roleId, index + 1);
      lines.push(`cat > ${shellQuote(file.path)} <<'${delimiter}'`);
      lines.push(file.content);
      lines.push(delimiter);
      lines.push(`chmod ${file.mode} ${shellQuote(file.path)}`);
    });
    lines.push("");
  });

  return `${lines.join("\n")}\n`;
}

function buildRoleWorkspaceScaffold(
  workPackage: TeamWorkPackage,
  generatedAt: string
): RoleWorkspaceScaffold {
  const rootPath = `team-workspaces/${safePathSegment(workPackage.roleId)}`;
  const files = [
    workspaceFile(rootPath, "README.md", "readme", readmeContent(workPackage, generatedAt)),
    workspaceFile(rootPath, ".env.example", "env-example", envExampleContent(workPackage)),
    workspaceFile(rootPath, "tasks.md", "tasks", taskContent(workPackage)),
    workspaceFile(rootPath, "runner-notes.md", "runner-notes", runnerNotesContent(workPackage)),
    workspaceFile(rootPath, "security.md", "security", securityContent(workPackage))
  ];

  return {
    id: `${workPackage.roleId}-workspace-scaffold`,
    packageId: workPackage.id,
    roleId: workPackage.roleId,
    roleName: workPackage.roleName,
    ministry: workPackage.ministry,
    rootPath,
    status: workPackage.status,
    providerAlias: workPackage.provider.apiKeyAlias,
    executorProfileId: workPackage.executorProfileId,
    files,
    commands: [
      `cp ${rootPath}/.env.example ${rootPath}/.env.local`,
      `open ${rootPath}/README.md`
    ],
    generatedAt
  };
}

function workspaceFile(
  rootPath: string,
  name: string,
  purpose: RoleWorkspaceFile["purpose"],
  content: string
): RoleWorkspaceFile {
  return {
    path: `${rootPath}/${name}`,
    purpose,
    mode: "0644",
    content
  };
}

function readmeContent(workPackage: TeamWorkPackage, generatedAt: string) {
  return [
    `# ${workPackage.roleName} Workspace`,
    "",
    `Mission: ${workPackage.mission}`,
    `Ministry: ${workPackage.ministry}`,
    `Stage: ${workPackage.stageId}`,
    `Status: ${workPackage.status}`,
    `Generated: ${generatedAt}`,
    "",
    "## Provider",
    `- Provider: ${workPackage.provider.provider}`,
    `- Model: ${workPackage.provider.model}`,
    `- Endpoint: ${workPackage.provider.endpoint}`,
    `- API key alias: ${workPackage.provider.apiKeyAlias || "ROLE_API_KEY_ALIAS"}`,
    "",
    "## Objectives",
    ...list(workPackage.objectives),
    "",
    "## Dependencies",
    ...list(workPackage.dependencies),
    "",
    "## Deliverables",
    ...list(workPackage.deliverables)
  ].join("\n");
}

function envExampleContent(workPackage: TeamWorkPackage) {
  const apiAlias = workPackage.provider.apiKeyAlias.trim();
  return [
    "# Copy this file to .env.local for this role workspace.",
    "# Keep .env.local out of Git. Fill real secrets only in your local environment or vault.",
    `NAIKAKU_ROLE_ID=${workPackage.roleId}`,
    `NAIKAKU_ROLE_NAME=${shellEnvValue(workPackage.roleName)}`,
    `NAIKAKU_MINISTRY=${shellEnvValue(workPackage.ministry)}`,
    `NAIKAKU_PROVIDER=${workPackage.provider.provider}`,
    `NAIKAKU_MODEL=${shellEnvValue(workPackage.provider.model)}`,
    `NAIKAKU_ENDPOINT=${shellEnvValue(workPackage.provider.endpoint)}`,
    `NAIKAKU_API_KEY_ALIAS=${shellEnvValue(apiAlias || "ROLE_API_KEY_ALIAS")}`,
    `NAIKAKU_EXECUTOR_PROFILE=${workPackage.executorProfileId}`,
    "",
    envAliasLine(apiAlias)
  ].join("\n");
}

function taskContent(workPackage: TeamWorkPackage) {
  return [
    `# ${workPackage.roleName} Tasks`,
    "",
    "## Work",
    ...checklist(workPackage.tasks),
    "",
    "## Acceptance Criteria",
    ...checklist(workPackage.acceptanceCriteria),
    "",
    "## Automation Action IDs",
    ...list(workPackage.automationActionIds)
  ].join("\n");
}

function runnerNotesContent(workPackage: TeamWorkPackage) {
  return [
    `# ${workPackage.roleName} Runner Notes`,
    "",
    `Executor profile: ${workPackage.executorProfileId}`,
    "",
    "## Permissions",
    ...permissionLines(workPackage.permissions),
    "",
    "## Suggested Commands",
    "- Start from the team package JSON before wiring live providers.",
    "- Run tests and capture evidence before marking tasks done.",
    "- Attach screenshots, command transcripts, or logs to the issue or handoff."
  ].join("\n");
}

function securityContent(workPackage: TeamWorkPackage) {
  return [
    `# ${workPackage.roleName} Security Notes`,
    "",
    "## Required Guardrails",
    ...list(workPackage.securityNotes),
    "",
    "## Local Rules",
    "- Do not commit .env.local or raw provider keys.",
    "- Use provider aliases in exported artifacts.",
    "- Keep high-impact actions behind approval gates.",
    "- Preserve audit evidence for every executor action."
  ].join("\n");
}

function list(items: string[]) {
  return items.length ? items.map((item) => `- ${item}`) : ["- None"];
}

function checklist(items: string[]) {
  return items.length ? items.map((item) => `- [ ] ${item}`) : ["- [ ] Define before implementation starts."];
}

function permissionLines(permissions: RolePermissions) {
  return [
    `- Browser: ${yesNo(permissions.canUseBrowser)}`,
    `- Shell: ${yesNo(permissions.canUseShell)}`,
    `- Files: ${yesNo(permissions.canUseFiles)}`,
    `- Network: ${yesNo(permissions.canSendNetworkRequests)}`,
    `- Human approval for high impact: ${yesNo(permissions.requiresApprovalForHighImpact)}`
  ];
}

function envAliasLine(apiAlias: string) {
  const alias = oneLine(apiAlias);
  if (!alias) {
    return "# ROLE_API_KEY_ALIAS=fill-in-local-secret";
  }
  if (!/^[A-Z_][A-Z0-9_]*$/.test(alias)) {
    return `# ${alias}=fill-in-local-secret`;
  }
  return `${alias}=`;
}

function shellEnvValue(value: string) {
  return `"${oneLine(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function summaryKey(status: TeamPackageStatus): keyof ScaffoldSummaryCounts {
  if (status === "needs-approval") return "needsApproval";
  if (status === "template") return "templates";
  return status;
}

function safePathSegment(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 72) || "role";
}

function shellQuote(value: string) {
  return `'${value.split("'").join("'\\''")}'`;
}

function heredocDelimiter(content: string, roleId: string, fileNumber: number) {
  let delimiter = `NAIKAKU_${safePathSegment(roleId).replace(/-/g, "_").toUpperCase()}_${fileNumber}`;
  while (content.includes(delimiter)) {
    delimiter = `${delimiter}_X`;
  }
  return delimiter;
}

function oneLine(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function yesNo(value: boolean) {
  return value ? "yes" : "no";
}
