server {
    listen 80;
    listen [::]:80;
    server_name naikaku.emysti.net;

    root /var/www/naikaku-emysti-net;
    index index.html;

    location = / {
        return 301 /ja/;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
